/*
   This file was generated automatically by Alchitry Labs version 1.2.0.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module full_adder_6 (
    input cin,
    input x,
    input y,
    output reg s,
    output reg cout
  );
  
  
  
  always @* begin
    cout = cin & x | cin & y | x & y;
    s = x ^ y ^ cin;
  end
endmodule
